export const selectors = {
  arrButton: '.filter-tab .arr',
  card: '.card',
  citiesContainer: '.cities-container',
  citiesInput: '.popup-container input[type="text"]',
  cityListEl: '.city-list-el',
  cityListLetter: '.city-list-letter',
  cityListLink: '.city-list-link',
  error: '.error',
  executeButton: '.execute',
  filters: '.filter-area.hide-desc .filter:not(.sort)',
  filtersPopup: '.popup.filters .filter-area .filter:not(.sort)',
  filterText: '.filter-tab .text',
  firstMonth: '.action-mark.first-month',
  formStateDefault: '[data-state="default"]',
  formStateError: '[data-state="error"]',
  formStateSuccess: '[data-state="success"]',
  hidden: 'hidden',
  icon: '.icon-container .icon',
  iconContainer: '.icon-container',
  iconInfo: '.icon-info',
  iconOpened: '.icon.opened',
  input: 'input',
  inputArea: '.filter-items',
  item: '.item',
  monthWord: '.month-word',
  nameInput: 'label.text-input[data-type="name"]',
  oldPrice: '.old-price',
  orderForm: '.order-form',
  phoneInput: 'label.text-input[data-type="phone"]',
  popup: '.popup',
  popupCloseButton: '.close-icon',
  popupContainer: '.popup-container',
  popupCities: '.popup.cities',
  popupFilters: '.popup.filters',
  popupOrderForm: '.popup.order-form',
  price: '.current-price .digits',
  promoInfo: '.action-mark.action-length',
  promoLength: '.promo-length',
  promoPercent: '.percent',
  rangeInput: 'input[type="range"]',
  resetButton: '.reset',
  reset: '.reset',
  showFilterContainer: '.show-filter-container',
  showMoreButton: 'button.show-more',
  showMoreContainer: '.show-more-container',
  sortContainer: '.filter-area.hide-desc .filter.sort',
  sortPopupContainer: '.popup.filters .filter.sort',
  speeds: '.range-speeds span',
  speed: '.speed',
  submitButton: 'button[type="submit"]',
  tariffCardsContainer: '.tariffs',
  tariffsContainer: '.tariffs-container',
  text: '.text',
  textInput: 'label.text-input[data-type="text"]',
  thanksButton: '[data-state="success"] .button',
};

export const classes = {
  active: 'active',
  icon: 'icon',
  error: 'error',
  filling: 'filling',
  filled: 'filled',
  focus: 'focus',
  found: 'found',
  opened: 'opened',
  popupOverlay: 'overlay',
};

export const attributes = {
  additonalText: 'data-additional_text',
  allSelectedText: 'data-all_text',
  defaultText: 'data-default_text',
  disabled: 'disabled',
  filtered: 'data-filtered',
  filterExecuteProperty: 'filter-execute_property',
  filterByProvider: 'filter_by-provider',
  filterBySpeed: 'filter_by-speed',
  filterByTariffType: 'filter_by-tariff-type',
  filterType: 'filter-type',
  find: 'data-find',
  options: 'data-options',
  sortAction: 'sort-action',
  sortMaxPrice: 'sort-max_price',
  sortPopularity: 'sort-popularity',
  sortPrice: 'sort-price',
  sortSpeed: 'sort-speed',
};
